In [24]:
%pip install tensorflow
%pip install keras

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [25]:
from tensorflow.keras.preprocessing.text import one_hot

In [26]:
sent = [  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [27]:
voc_size = 10000

In [28]:
one_hot_rep = [one_hot(words,voc_size)for words in sent]
one_hot_rep

[[9134, 1276, 3305, 3011],
 [9134, 1276, 3305, 1847],
 [9134, 5724, 3305, 9098],
 [5693, 8480, 9687, 7866, 7138],
 [5693, 8480, 9687, 7866, 7881],
 [9577, 9134, 4919, 3305, 9009],
 [4142, 9164, 2174, 7866]]

In [29]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [30]:
import numpy as np

In [31]:
sent_len = 8
embedded_docs = pad_sequences(one_hot_rep, padding = 'pre', maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 9134 1276 3305 3011]
 [   0    0    0    0 9134 1276 3305 1847]
 [   0    0    0    0 9134 5724 3305 9098]
 [   0    0    0 5693 8480 9687 7866 7138]
 [   0    0    0 5693 8480 9687 7866 7881]
 [   0    0    0 9577 9134 4919 3305 9009]
 [   0    0    0    0 4142 9164 2174 7866]]


In [32]:
#feature representation
dim = 10

In [33]:

model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

/Users/reetjirety/Desktop/DA_GenAI_SD/Gen_AI/annclassification/venv/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [34]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step


array([[[-0.03844932,  0.04591182, -0.01440092, -0.03200554,
         -0.03509124,  0.02547506, -0.02539626, -0.00576701,
          0.01962968, -0.04614649],
        [-0.03844932,  0.04591182, -0.01440092, -0.03200554,
         -0.03509124,  0.02547506, -0.02539626, -0.00576701,
          0.01962968, -0.04614649],
        [-0.03844932,  0.04591182, -0.01440092, -0.03200554,
         -0.03509124,  0.02547506, -0.02539626, -0.00576701,
          0.01962968, -0.04614649],
        [-0.03844932,  0.04591182, -0.01440092, -0.03200554,
         -0.03509124,  0.02547506, -0.02539626, -0.00576701,
          0.01962968, -0.04614649],
        [ 0.01804204,  0.02299482, -0.01811635,  0.04820316,
         -0.0275884 , -0.04051309, -0.03638359, -0.03237821,
         -0.00050963,  0.04013094],
        [ 0.00695913,  0.04631057,  0.01037077,  0.01100198,
          0.00187756, -0.02313113, -0.03756236, -0.04461829,
         -0.01517618,  0.02993302],
        [-0.02111706, -0.04019944,  0.03628545, -0.0

In [37]:
embedded_docs[0]

array([   0,    0,    0,    0, 9134, 1276, 3305, 3011], dtype=int32)

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>